In [46]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  5 21:02:20 2018

@author: rosannaz
"""

import csv

# Load the Pandas libraries with alias 'pd' 
import pandas as pd 
# Read data from file 'filename.csv' 
data = pd.read_csv("AllDeals05-18-clean.csv") 
# Preview the first 5 lines of the loaded data 
data.head()

,Name,Stage,Date,Size,TotalFunding,Investors,State,IndustryClassification,PrimaryIndustry,Sub-Industries,Status
0,#waywire,Seed,6/30/12,1.75,1.75,"First Round Capital, Innovation Endeavors",New York,Internet,Internet,"Multimedia & Graphics, Social Networking & Com...",Realised
1,"@RISK Technologies, Inc.",Seed,3/14/17,2.00,2.00,NaN,Texas,Other IT,IT Security,"Analytics & Performance Software, Monitoring &...",Active
2,@WalmartLabs,Series B/Round 2,1/1/06,18.00,55.23,"Accel, Lightspeed Venture Partners",California,Internet,Internet,"Search Engines, Domain & SEO Services, Social ...",Realised
3,@WalmartLabs,Series C/Round 3,12/1/07,10.00,55.23,"Accel, DAG Ventures, Lightspeed Venture Partners",California,Internet,Internet,"Search Engines, Domain & SEO Services, Social ...",Realised
4,@WalmartLabs,Series D/Round 4,12/8/08,20.00,55.23,"Accel, DAG Ventures, Lightspeed Venture Partne...",California,Internet,Internet,"Search Engines, Domain & SEO Services, Social ...",Realised

In [47]:
list(data)

['Name',
 'Stage',
 'Date',
 'Size',
 'TotalFunding',
 'Investors',
 'State',
 'IndustryClassification',
 'PrimaryIndustry',
 'Sub-Industries',
 'Status']

In [48]:
data = data.dropna()

In [49]:
data.Status = data.Status.astype('category')
data.Status = data.Status.cat.codes
data.Stage = data.Stage.astype('category')
data.Stage = data.Stage.cat.codes
data.State = data.State.astype('category')
data.State = data.State.cat.codes
data.Name = data.Name.astype('category')
data.Name = data.Name.cat.codes
data.IndustryClassification = data.IndustryClassification.astype('category')
data.IndustryClassification = data.IndustryClassification.cat.codes

In [50]:
feature_cols = ['Name',
 'Stage',
 'Size',
 'TotalFunding',
 'State',
 'IndustryClassification']


X = data.dropna().loc[:, feature_cols]
y = data.dropna().Status

In [72]:
y = y.astype('category')
y = y.cat.codes
X.Stage = X.Stage.astype('category')
X.Stage = X.Stage.cat.codes
X.State = X.State.astype('category')
X.State = X.State.cat.codes
X.Name = X.Name.astype('category')
X.Name = X.Name.cat.codes
X.IndustryClassification = X.IndustryClassification.astype('category')
X.IndustryClassification = X.IndustryClassification.cat.codes

In [51]:
from sklearn.model_selection import train_test_split, GridSearchCV
# Partition data set into training/test split (2 to 1 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/10., random_state=42)

In [52]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [53]:
clf.fit(X_train, y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [55]:
predict = list(clf.predict(X_test))

In [56]:
y_p = list(y_test)

In [85]:
count = 0
for i in range(len(y_p)):
    if predict[i] == y_p[i]:
        count+=1

In [86]:
count

2208

In [92]:
X_test

        Name  Stage   Size  TotalFunding  State  IndustryClassification
6240    2333      2   2.50         37.50      4                      13
14694   5348      4  10.00         54.50     21                       1
25102   8995      2   0.13          1.13     32                       8
36402  12979      2   0.60        333.32      4                      13
18000   6464      2   2.00         58.00      4                      13
29173  10468      2   2.30          2.30      4                      14
21683   7781      2   1.00          4.13      4                      14
32883  11782      8  50.00        140.10     43                       8
36775  13106      3  10.00         12.82      4                      13
2616     975      5  35.20        195.53     33                       5
6196    2320      2   0.33          0.48     47                      13
29824  10731      2   1.50         18.00      4                       5
26349   9434      4  15.00         85.60      4                      12
32147  11523      4  11.00         14.90     46                      13
7482    2801      3   8.70         33.80     37                      10
11403   4186      3  15.50         55.50      4                       8
21999   7894      5   3.50         78.68     43                       5
3938    1455      3   7.00         18.50      4                      13
9122    3370      6  32.00        157.17      4                       5
34287  12288      4  18.50         36.00     32                      13
22303   7992      3   4.00        258.52      4                      13
31921  11462      2   3.33         38.33     14                      13
3137    1168      3   8.00         73.00      4                       2
20387   7338      3  12.60         59.60      4                      13
22970   8231      5  14.00         24.40      4                      12
8370    3102      6  19.40        186.31      5                       1
14010   5115      5  11.00        115.80      4                      13
24118   8630      6  50.00        126.57      4                       8
5002    1847      5  45.00        350.60     21                       1
459      119      4  10.00         67.00      4                      12
...      ...    ...    ...           ...    ...                     ...
14362   5235      2   2.50        115.56      4                      13
37969  13540      3   7.00          7.00      4                       4
11942  14413      4  16.00         18.80     32                       8
26133   8949      2   1.40          1.40      4                       8
21283   7642      2   2.50         57.75      4                      13
37986  13545      4  15.00         17.00     43                       5
16096  14450      5  23.00         93.50      4                      13
18730   6716      2   1.00          5.00      4                      13
17882   6409      2   0.50         11.20     32                      14
27229   9756      6  15.00        165.20      4                      13
11546   4241      4  32.00         61.50     21                       5
3254    1207      3   6.00         72.82      4                       5
10694   3950      4  29.00         44.00     47                      10
16789   6078      3   0.25          0.25     35                      10
30471  10942      2   2.50         10.60      4                       2
34581  12386      5   7.00         54.40      4                      13
33007  11826      2   2.00          4.30      4                      13
31578  11335      4  10.00        174.00     32                      13
19098   6862      4  34.00        167.00     32                       0
6930    2569      3   7.00         19.52      4                      13
32476  11642      6   4.50         27.53      4                      10
31272  11228      4  15.00         26.70      4                      13
36589  13038      4  75.00        135.10      4                       5
25814   9251      6   9.00         46.09      4                      14
32963  11811      3   5.50          7.00      4                       5
13503   4925      2   0.32          4.13     30                       8
17268   6235      3   3.00          3.15      4                       4
5852    2212      2   2.00         72.00     44                      13
28217  10137      4   4.60         19.72     23                       5
11843   4322      4  10.00         14.00     21                      14

[2708 rows x 6 columns]

In [57]:
clf.score(X_test, y_test)

0.81536189069423926

In [88]:
from sklearn.metrics import accuracy_score
accuracy_score(y_p, predict)

0.81536189069423926

In [62]:
import numpy as np
data['Date']=data['Date'].astype(str).str[-2:].astype(np.int64)
data.Date = data.Date.astype(int)

#In [11]: df = pd.DataFrame(np.random.randn(100, 2))

#In [12]: msk = np.random.rand(len(df)) < 0.8

#In [13]: train = df[msk]

#In [14]: test = df[~msk]

In [74]:
data_p = data.loc[data['Date'].between(4, 10)]
Xp = data_p.dropna().loc[:, feature_cols]
yp = data_p.dropna().Status
p = clf.predict(Xp)

In [79]:
Xp['Predict']=p
Xp['Status']=yp
Xp['Date']= data_p.Date
X_port = Xp.loc[Xp['Status']==1]

In [80]:
X_port.sample(50)

,Name,Stage,Size,TotalFunding,State,IndustryClassification,Predict,Status,Date
25022,8936,6,38.30,124.30,4,12,1,1,7
30578,10975,4,18.00,30.00,21,5,1,1,10
8971,3315,2,0.03,0.03,4,8,1,1,10
24828,8871,3,1.50,3.80,43,8,1,1,10
32475,11642,5,3.00,27.53,4,10,1,1,9
11485,4221,3,8.00,9.20,9,5,1,1,9
16359,14465,4,4.25,8.20,37,10,1,1,8
11253,4136,3,29.00,119.05,46,10,1,1,10
36322,12961,4,26.25,167.25,4,14,1,1,7
24563,8783,4,14.00,65.70,46,13,1,1,8
15458,5621,4,5.50,12.00,4,14,1,1,9
28577,10287,3,3.50,8.11,4,8,1,1,8
35622,12206,4,13.50,31.70,32,13,1,1,9
37569,13411,5,6.00,37.72,21,10,1,1,10
9455,3517,2,1.15,2.15,4,8,0,1,8
29207,10482,4,10.00,23.30,4,14,1,1,8
9494,14355,5,6.00,82.66,4,14,1,1,8
4054,1493,4,10.00,87.00,32,8,1,1,10
33890,12124,4,10.00,14.00,4,8,1,1,9
23317,8341,6,15.00,74.60,43,10,1,1,9
7734,2859,5,15.00,34.00,4,13,1,1,6
23491,8400,6,10.00,24.50,29,10,1,1,8
32556,11668,4,6.50,53.24,2,1,1,1,7
13988,5107,5,4.50,22.33,4,10,1,1,8
21060,7571,4,13.00,17.10,38,8,1,1,8
21841,7841,4,10.22,20.22,4,12,1,1,7
17599,6318,4,5.00,6.00,4,8,1,1,9
25687,9202,3,7.40,22.40,47,14,1,1,6
26512,9485,3,6.50,46.30,4,8,1,1,7
4335,1571,8,40.00,137.98,21,5,1,1,9
6078,2291,5,17.85,42.25,2,5,1,1,7
23457,8388,6,60.00,119.00,4,8,1,1,8
14560,5294,4,36.60,81.71,4,14,1,1,7
9062,3347,3,8.75,40.75,4,8,1,1,7
4626,1705,3,9.00,51.05,4,8,1,1,10
28487,10253,4,8.00,14.00,4,1,1,1,10
30623,10997,3,1.10,5.30,47,5,1,1,10
34593,12392,5,20.00,105.00,4,13,1,1,5
12372,4515,4,12.00,45.00,4,5,1,1,10
15603,5666,4,1.60,6.84,4,8,1,1,10
692,303,6,10.00,169.00,4,13,1,1,8
28380,10215,4,6.50,86.40,43,13,1,1,5
962,294,2,1.00,1.00,4,14,1,1,9
30862,11076,5,25.00,94.73,4,14,1,1,9
37628,13429,3,10.00,86.00,37,13,1,1,10
9948,3697,5,17.50,66.20,4,12,1,1,7
27256,9764,0,0.95,1.31,32,8,1,1,10
9565,3553,5,2.80,6.80,32,2,1,1,7
11581,4249,3,12.00,12.00,30,5,1,1,6
16592,6017,3,9.50,161.88,47,1,1,1,7

In [68]:
clf.score(Xp, yp)

0.95009953550099535

In [40]:
#Performance Test
#perform = data.loc[:, 4 <= data['Date'] <= 10]

data.Status = data.Status.astype('category')

feature_cols = ['Name',
 'Stage',
 'Size',
 'TotalFunding',
 'State',
 'IndustryClassification',
               'Date']

feature_cols2 = ['Name',
 'Stage',
 'Size',
 'TotalFunding',
 'State',
 'IndustryClassification',
               'Date']

#include date in equation, so we can then split data into pre 2010 and after 2010
Xp = data.dropna().loc[:, feature_cols]
yp = data.dropna().loc[:, ['Status', 'Date']]
from sklearn.model_selection import train_test_split, GridSearchCV
# Partition data set into training/test split (2 to 1 ratio)
Xp_train, Xp_test, yp_train, yp_test = train_test_split(X, y, test_size=1/10., random_state=42)

Xp_train = Xp_train.loc[:, feature_cols2]
yp_train = yp_train.Status

Xp_test = Xp_test.loc[:, 4 <= data['Date'] <= 10]
Xp_test = Xp_train.loc[:, feature_cols2]

yp_test = yp_test.loc[:, 4 <= data['Date'] <= 10]
yp_test = yp_test.Status

def training(X_train, y_train, X_test):
    from sklearn import svm
    clf = svm.SVC(gamma=0.001, C=100.)
    clf.fit(X_train, y_train)
    return clf.predict(X_test)

p_predict = training(Xp_train, yp_train, Xp_test)

AttributeError: 'Series' object has no attribute 'Status'

In [33]:
from datetime import datetime

datetime_object = datetime.strptime('1/1/2010')

TypeError: strptime() takes exactly 2 arguments (1 given)

In [ ]:
clf.score(X_test, y_test)

In [61]:
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
enc = preprocessing.OrdinalEncoder()
enc.fit(y) 
enc.transform(y)

ImportError: cannot import name 'OrdinalEncoder'